services:
  api:
    container_name: galactic-archives-api-dev
    image: galactic-archives-api-dev
    build:
      context: ../../
      dockerfile: ./Docker/dev/Dockerfile
    environment:
      - ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ASPNETCORE_URLS=https://0.0.0.0:443;http://0.0.0.0:80
      - Kestrel__Certificates__Default__Path=/app/cert-aspnetcore.pfx
      - Kestrel__Certificates__Default__Password=cheese
    ports:
      - 5001:80
      - 7009:443

